config/routes.rb
Cultivate::Application.routes.draw do

  resources :plants

  resources :users

  match '/garden', to: 'plants#index', via: 'get'
  match "/contact", to: 'home#contact', via: 'get'
  match 'sign_up', to: 'users#new', via: 'get'

  root 'home#index'

end

app/models/plant.rb
class Plant < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@go_green = params[:go_green]
  end

  def contact
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plant }
      else
        format.html { render action: 'new' }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.require(:plant).permit(:lifecycle, :plant_type, :breed, :sun_preference, :soil_type)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :bio, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def greenify
		if params[:go_green].to_i == 1
			"class=greenify"
		else
			"class=default"
		end
	end

end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<% provide 'app/helpers/home_helper.rb' %>

<div class="hero center jumbotron">

	<div <%= greenify %>>
		<h1>Welcome back to the land.</h1>
	</div>

	<p>Cultivate is a web app that helps people manage small farms and gardens. </p>
	<p>We help keep your animals and agriculture organized, so you can spend more time celebrating the harvest.</p><br />

	<div class="center">
		<%= link_to "Sign up", sign_up_path, class: "btn btn-lg btn-warning center", role: "button" %><br /><br />

		<%= link_to "Go Green!", root_path(go_green: 1) %>
	</div>

</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Cultivate", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li>
						<div class="dropdown">
	   				 
	   				 <a data-target="#" href="<%= garden_path %>" data-toggle="dropdown" class="dropdown-toggle">Garden <b class="caret"></b></a>
		   				
		   				<ul class="dropdown-menu">
				        
				        <li><a href="#">My Gardens</a></li>
				        <li><a href="#">My Plants</a></li>
				        <li><a href="#">My Seedlings</a></li>
				        <li><a href="#">Seed Bank</a></li>
				        <li class="divider"></li>
						    <li><%= link_to "Browse Gardens", garden_path %></li>
						  
						  </ul>   

						</div>
					</li>
					<li>
						<div class="dropdown">
	   				 
	   				 <a data-target="#" href="#" data-toggle="dropdown" class="dropdown-toggle">Barnyard<b class="caret"></b></a>
		   				
		   				<ul class="dropdown-menu">
				        
				        <li><a href="#">My Chickens</a></li>
				        <li><a href="#">My Goats</a></li>
				        <li><a href="#">My Sheep</a></li>
				        <li><a href="#">Apiary</a></li>
				        <li class="divider"></li>
						    <li><%= link_to "Browse Barnyards", "#" %></li>
						  
						  </ul>   

						</div>
					</li>
					<li>
						<div class="dropdown">
	   				 
	   				 <a data-target="#" href="#" data-toggle="dropdown" class="dropdown-toggle">Porch<b class="caret"></b></a>
		   				
		   				<ul class="dropdown-menu">
				        
				        <li><a href="#">Messages</a></li>
				        <li><a href="#">Forum</a></li>
				        <li><a href="#">Random Advice</a></li>

						  </ul>   

						</div>
					</li>

					<li>
						<div class="dropdown">
	   				 
	   				 <a data-target="#" href="#" data-toggle="dropdown" class="dropdown-toggle">Log in <b class="caret"></b></a>
		   				
		   				<ul class="dropdown-menu">
				        
				        <li><a href="#">Username</a></li>
				        <li><a href="#">Password</a></li>
				        
				        <li class="divider"></li>
						    <li><%= link_to "Sign up", sign_up_path %></li>
						    <li><a href="#">Help</a></li>
						  </ul>   

						</div>
					</li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Cultivate</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
		</div>
		<%# render 'layouts/footer' %>
	</body>
</html>

app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lifecycle %><br>
    <%= f.text_field :lifecycle %>
  </div>
  <div class="field">
    <%= f.label :plant_type %><br>
    <%= f.text_field :plant_type %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :sun_preference %><br>
    <%= f.text_field :sun_preference %>
  </div>
  <div class="field">
    <%= f.label :soil_type %><br>
    <%= f.text_field :soil_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing plant</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<h1>Listing plants</h1>

<table>
  <thead>
    <tr>
      <th>Lifecycle</th>
      <th>Plant type</th>
      <th>Breed</th>
      <th>Sun preference</th>
      <th>Soil type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.lifecycle %></td>
        <td><%= plant.plant_type %></td>
        <td><%= plant.breed %></td>
        <td><%= plant.sun_preference %></td>
        <td><%= plant.soil_type %></td>
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant', new_plant_path %>

app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lifecycle:</strong>
  <%= @plant.lifecycle %>
</p>

<p>
  <strong>Plant type:</strong>
  <%= @plant.plant_type %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @plant.breed %>
</p>

<p>
  <strong>Sun preference:</strong>
  <%= @plant.sun_preference %>
</p>

<p>
  <strong>Soil type:</strong>
  <%= @plant.soil_type %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Bio</th>
      <th>Location</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.bio %></td>
        <td><%= user.location %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container hero center sign-up">

	<h1 class=>Sign Up!</h1>

	<%= render 'form' %>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>